services:
  redis:
    build: ./bin/redis
    container_name: redis
    restart: ${RESTART}
    volumes:
      - "/data/mailu/redis:/data"
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - default
  mysql8:
    build: ./bin/mysql8
    container_name: default-mysql8
    restart: ${RESTART}
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - '${MYSQL_DATA_DIR8-./data/mysql8}:/var/lib/mysql'
      - '${MYSQL_LOG_DIR8-./logs/mysql8}:/var/log/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - default
  phpmyadmin:
    build: ./bin/phpmyadmin
    container_name: default-phpmyadmin
    restart: ${RESTART}
    links:
      - mysql
    environment:
      PMA_HOST: mysql8
      PMA_PORT: ${MYSQL_PORT}
    ports:
      - '${PHPMYADMIN_PORT}:80'
    volumes:
      - /sessions
    networks:
      - default
  blackfire:
    container_name: default-blackfire
    build:
      context: ./bin/blackfire
    ports:
      - '${BLACKFIRE_PORT}:8707'
    restart: ${RESTART}
    environment:
      BLACKFIRE_SERVER_ID: "${BLACKFIRE_SERVER_ID}"
      BLACKFIRE_SERVER_TOKEN: "${BLACKFIRE_SERVER_TOKEN}"
      BLACKFIRE_CLIENT_ID: " ${BLACKFIRE_CLIENT_ID}"
      BLACKFIRE_CLIENT_TOKEN:  "${BLACKFIRE_CLIENT_TOKEN}"
    networks:
      - default
  minio:
    build: ./bin/minio
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
      MINIO_BUCKET_NAME: meu-bucket
    volumes:
      - ./data/minio:/data
    ports:
      - "${MINIO_PORT1}:9000"
      - "${MINIO_PORT2}:9001"
    command: server /data --console-address ":9001"
    networks:
      - default
networks:
  default:
    driver: bridge