version: '3'
services:
  redis:
    build: ./bin/redis
    container_name: redis
    restart: ${RESTART}
    volumes:
      - "/data/mailu/redis:/data"
    ports:
      - '6379:6379'
    networks:
      - default
  mysql:
    build: ./bin/mysql
    container_name: default-mysql
    restart: ${RESTART}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - '${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql'
      - '${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql'
    ports:
      - '3306:3306'
    networks:
      - default
networks:
  default:
    driver: bridge