version: '3'
services:
  redis:
    build: ./bin/redis
    container_name: redis
    restart: ${RESTART}
    volumes:
      - "/data/mailu/redis:/data"
    ports:
      - '6379:6379'
    networks:
      - default
  mysql:
    build: ./bin/mysql
    container_name: default-mysql
    restart: ${RESTART}
    ports:
      - '3306:3306'
    volumes:
      - '${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql'
      - '${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - default
  mysql8:
    build: ./bin/mysql-8
    container_name: default-mysql-8
    restart: ${RESTART}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_TCP_PORT: "3307"
    ports:
      - '3307:3306'
    networks:
      - default
networks:
  default:
    driver: bridge