version: '3'
services:
  redis:
    build: ./bin/redis
    container_name: redis
    restart: ${RESTART}
    volumes:
      - "/data/mailu/redis:/data"
    ports:
      - '6379:6379'
    networks:
      - default
  mysql:
    build: ./bin/mysql
    container_name: default-mysql
    restart: ${RESTART}
    ports:
      - '3306:3306'
    volumes:
      - '${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql'
      - '${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - default
  php:
    build: ./bin/code-quality/php
    container_name: code_quality
    restart: ${RESTART}
    volumes:
      - ./www:/usr/share/apache2/www
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - default
networks:
  default:
    driver: bridge