services:
  redis:
    build: ./bin/redis
    container_name: redis
    restart: ${RESTART}
    volumes:
      - "/data/mailu/redis:/data"
    ports:
      - '6379:6379'
    networks:
      - default

  mysql8:
    build: ./bin/mysql8
    container_name: default-mysql8
    restart: ${RESTART}
    ports:
      - '3307:3306'
    volumes:
      - '${MYSQL_DATA_DIR8-./data/mysql8}:/var/lib/mysql'
      - '${MYSQL_LOG_DIR8-./logs/mysql8}:/var/log/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - default

  minio:
    build: ./bin/minio
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 12345678
      MINIO_BUCKET_NAME: meu-bucket
    volumes:
      - ./data/minio:/data
    ports:
      - "9100:9000"
      - "9101:9001"
    command: server /data --console-address ":9001"
    networks:
      - default

networks:
  default:
    driver: bridge