version: '3'
services:
  redis:
    build: ./bin/redis
    container_name: redis
    restart: ${RESTART}
    volumes:
      - "/data/mailu/redis:/data"
    ports:
      - '6379:6379'
    networks:
      - default
networks:
  default:
    driver: bridge